import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./(frontend)/components/navbar";
import SideMenu from "./(frontend)/components/sidemenu";
import Footer from "./(frontend)/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      
          <body className={inter.className}>

          <Navbar/> 
            
            <div className="flex">
            
              <SideMenu />
                <div className=" min-w-screen w-full bg-gray-1100" >
                  
                <div className="min-h-screen w-full">
                 {children}
                </div>
                  <Footer /> 
              </div>
                
            </div>
            
          </body>

      

    </html>
  );
}
